# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lottery_bowl_pb2 as lottery__bowl__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lottery_bowl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BowlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GrabLot = channel.unary_unary(
                '/BowlService/GrabLot',
                request_serializer=lottery__bowl__pb2.GrabLotRequest.SerializeToString,
                response_deserializer=lottery__bowl__pb2.Lot.FromString,
                _registered_method=True)
        self.RefillBowl = channel.unary_unary(
                '/BowlService/RefillBowl',
                request_serializer=lottery__bowl__pb2.RefillBowlRequest.SerializeToString,
                response_deserializer=lottery__bowl__pb2.RefillBowlResponse.FromString,
                _registered_method=True)
        self.GetSize = channel.unary_unary(
                '/BowlService/GetSize',
                request_serializer=lottery__bowl__pb2.GetSizeRequest.SerializeToString,
                response_deserializer=lottery__bowl__pb2.GetSizeResponse.FromString,
                _registered_method=True)


class BowlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GrabLot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefillBowl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BowlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GrabLot': grpc.unary_unary_rpc_method_handler(
                    servicer.GrabLot,
                    request_deserializer=lottery__bowl__pb2.GrabLotRequest.FromString,
                    response_serializer=lottery__bowl__pb2.Lot.SerializeToString,
            ),
            'RefillBowl': grpc.unary_unary_rpc_method_handler(
                    servicer.RefillBowl,
                    request_deserializer=lottery__bowl__pb2.RefillBowlRequest.FromString,
                    response_serializer=lottery__bowl__pb2.RefillBowlResponse.SerializeToString,
            ),
            'GetSize': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSize,
                    request_deserializer=lottery__bowl__pb2.GetSizeRequest.FromString,
                    response_serializer=lottery__bowl__pb2.GetSizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BowlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BowlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BowlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GrabLot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BowlService/GrabLot',
            lottery__bowl__pb2.GrabLotRequest.SerializeToString,
            lottery__bowl__pb2.Lot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefillBowl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BowlService/RefillBowl',
            lottery__bowl__pb2.RefillBowlRequest.SerializeToString,
            lottery__bowl__pb2.RefillBowlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BowlService/GetSize',
            lottery__bowl__pb2.GetSizeRequest.SerializeToString,
            lottery__bowl__pb2.GetSizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
