# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lottery_bowl.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'lottery_bowl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12lottery_bowl.proto\"\x10\n\x0eGrabLotRequest\"\x10\n\x0eGetSizeRequest\"#\n\x03Lot\x12\x12\n\x05value\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_value\"#\n\x11RefillBowlRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"%\n\x12RefillBowlResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0fGetSizeResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x9a\x01\n\x0b\x42owlService\x12\"\n\x07GrabLot\x12\x0f.GrabLotRequest\x1a\x04.Lot\"\x00\x12\x37\n\nRefillBowl\x12\x12.RefillBowlRequest\x1a\x13.RefillBowlResponse\"\x00\x12.\n\x07GetSize\x12\x0f.GetSizeRequest\x1a\x10.GetSizeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lottery_bowl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRABLOTREQUEST']._serialized_start=22
  _globals['_GRABLOTREQUEST']._serialized_end=38
  _globals['_GETSIZEREQUEST']._serialized_start=40
  _globals['_GETSIZEREQUEST']._serialized_end=56
  _globals['_LOT']._serialized_start=58
  _globals['_LOT']._serialized_end=93
  _globals['_REFILLBOWLREQUEST']._serialized_start=95
  _globals['_REFILLBOWLREQUEST']._serialized_end=130
  _globals['_REFILLBOWLRESPONSE']._serialized_start=132
  _globals['_REFILLBOWLRESPONSE']._serialized_end=169
  _globals['_GETSIZERESPONSE']._serialized_start=171
  _globals['_GETSIZERESPONSE']._serialized_end=204
  _globals['_BOWLSERVICE']._serialized_start=207
  _globals['_BOWLSERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
